[package]
name = "slap"
version = "0.1.0"
edition = "2024"
description = "Create files and directories with ease - touch, but slappier"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
tempfile = "3"
